### PR TITLE
[Feat] sign in with google oauth2

### LINKED ISSUE #4: [Feat] sign in with google oauth2
## 🚀 Feature Request

- [x] modify user structure(it already exists)
- [x] add login api w/google oauth
- [x] verify email pattern (khu.ac.kr)

## 📎 Additional context

- I will modify jwt code after creating login logic

### PR DESCRIPTION
**Pull request by dusdjhyeon**
## Description

- You can login with google oauth.
- You can receive current user's email through the access token provided by google oauth.
- Only KyungHee Univ email account users will be saved in mysql.

## Problems
- The validity of the access token (bear type) provided by Google oauth is only 1 hour.
- After login, you will be redirected to the callback url. 
    - We need to redirect to two different pages depending on whether the user has previously signed up or not

## Additional
After login response : {"info": {"access_token:"~~~~", "token_type":"bearer"}, "member": bool}
If member key = true : The current user is already a subscribed user.

## Related Issue

close #4

### CODE REVIEW

**Comment by dusdjhyeon** [comment]
> ## Problems
> * The validity of the access token (bear type) provided by Google oauth is only 1 hour.
> * After login, you will be redirected to the callback url.
>   
>   * We need to redirect to two different pages depending on whether the user has previously signed up or not
> 


I'm going to leave a solution to the problems as a new issue. Please give me some advice.

**Comment by Eeap** [comment]
umm.. I think that It is no problem to set expired time just 1 hr. 
```After login, you will be redirected to the callback url. We need to redirect to two different pages depending on whether the user has previously signed up or not```
What do u mean? just different page rendering or separated callback url?

**Comment by dusdjhyeon** [comment]
> What do u mean? just different page rendering or separated callback url?

Maybe,,  the former. We only have one callback url that generates access token..(current state -> redirec_url = callback url)
But,, we want to return to the main page when a user who has already signed up comes, and to the additional input page when the first user is logged in.

**Comment by Eeap** [comment]
> > What do u mean? just different page rendering or separated callback url?
> 
> Maybe,, the former. We only have one callback url that generates access token..(current state -> redirec_url = callback url) But,, we want to return to the main page when a user who has already signed up comes, and to the additional input page when the first user is logged in.

I think its task is duty for FE. How about sending access token with response? If then, FE may render main page with access token
If there is no response about auth routing, other ways may be needed

**Review by Eeap — APPROVED** [review]
LGTM ^^

**Pull request merged**
